version: '3'
services:
  backend:
    build:
      context: ./quiz-api
      dockerfile: Dockerfile
    env_file:
      - ./quiz-api/.env
    ports:
      - 5000:5000
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - ./quiz-api:/app
    command: npm run dev

  frontend:
    build:
      context: ./quiz-react
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./quiz-react:/app

  # If Redis installed in Local, Comment out this part
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - app-network
 # End Here 

  #Pulling mongo (mongo:latest)... 
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./quiz-react/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
