version: '3'
services:
  backend:
    build:
      context: ./quiz-api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - ./quiz-api:/app
    command: npm run dev

  # frontend:
  #   build:
  #     context: ./quiz-react
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./quiz-react:/app

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - app-network

  # nginx:
  #   image: nginx:1.21
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./quiz-react/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
